allowBuilds:
  esbuild: set this to true or false
minimumReleaseAgeExclude:
  - '@esportsplus/typescript@0.34.4'
  - '@esportsplus/typescript@0.33.5 || 0.34.1'
  - '@esportsplus/cli-passthrough@0.0.15 || 0.0.18'
  - '@esportsplus/utilities@0.28.0 || 0.28.3'
  - tsc-alias@1.9.4
  - '@types/node@26.5.0'
onlyBuiltDependencies:
  - esbuild
strictDepBuilds: false
