name: bump version
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  bump:
    uses: esportsplus/typescript/.github/workflows/bump.yml@main
    with:
      release-revision: true
      patch-keywords: fix,chore,perf
      should-default-to-patch: true
